services:
  webapi:
    build:
      dockerfile: Dockerfile
    ports:
      - "7103:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DatabaseConfiguration__ConnectionString: "mongodb://mongo:27017"
    volumes:
      - ./MenuChooser-Api:/app
    command: ["dotnet", "watch", "run", "-v", "--project", "MenuChooser/MenuChooser.csproj", "--urls", "http://0.0.0.0:7103"]

  mongo:
    ports:
      - "27018:27017"
